### ISSUE TITLE
forward renderer has not any surface 

### ISSUE THREAD

**Issue by sajadblog** [KDAB/kuesa#142]
hi 
tnx for your project .
in any example that exist in source tree and other project that powered by kuesa for load gltf files there is a problem at  forwardRenderer.
when start application and try to create forwardRenderer there is no window in "currentSurface" variable and application pring qCWarning that say "unexpected surface size".
and finally cannot show any  3d item.

1   Kuesa::ForwardRenderer::currentSurfaceSize                                                          forwardrenderer.cpp 1321 0x7fffcd52f7fd 
2   Kuesa::ForwardRenderer::reconfigureFrameGraph                                                       forwardrenderer.cpp 1109 0x7fffcd52e842 
3   Kuesa::ForwardRenderer::rebuildFGTree                                                               forwardrenderer.cpp 1338 0x7fffcd52f973 
4   Kuesa::ForwardRenderer::ForwardRenderer                                                             forwardrenderer.cpp 620  0x7fffcd52d0b9 
5   QQmlPrivate::QQmlElement<Kuesa::ForwardRenderer>::QQmlElement                                       qqmlprivate.h       103  0x7fffcd9378eb 
6   QQmlPrivate::createInto<Kuesa::ForwardRenderer>                                                     qqmlprivate.h       124  0x7fffcd937926 
7   QQmlType::create(QObject * *, void * *, unsigned long) const                                                                 0x7ffff6accbf3 
8   QQmlObjectCreator::createInstance(int, QObject *, bool)                                                                      0x7ffff6b300ee

**Comment by sajadblog** [comment]
+ and there is not any External  Render Target at forwardRenderer

**Comment by sajadblog** [comment]
and at start messages show bellow text
Failed to load binary resources:  "/...../kdab/kuesa/debug/examples/kuesa/car-scene/resources/.."

**Comment by lemirep** [comment]
Hello @sajadblog,

I think your main issue is coming from the binary resources not being loaded.

Which examples are you trying to load and on which platform are you? 

We've just pushed a commit that fixes deployment of the resources on Windows. Maybe give it a try if you're on Windows. Otherwise we'll need to find why the resources are not deployed.

Also what you could do is try to locate the .qrb resource files from your build directory. They should be in a folder called resources. Then you could try to copy that resources folder alongside your binary (you would then have something like car-scene, resources/ both at the same directory level).

**Comment by sajadblog** [comment]
yes this error coming from  resources and finally solved.
at first git clone lfs can't load currently files and at second time that i clone repo all png files and resources clone perfectly.
tnx for your response
